"""Force one character's colours onto another's palette.

Characters generated by different modes do not share a palette - the quadruped rig
cannot take a reference sprite, so it comes back in its own colours and reads as a
different animal. This maps every colour in the source onto the nearest colour in
the reference by lightness, which keeps the shading structure intact while adopting
the reference's exact hues and, importantly, its outline colour.

Writes in place. The art is re-downloadable with fetch_character.py, so this is
recoverable, but run it on a fresh fetch rather than repeatedly over its own output.

Usage:  python match_palette.py <source_name> <reference_name>
"""
import collections
import glob
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CHARACTERS = ROOT / "cat-game" / "assets" / "characters"

## Colours covering less of the art than this are treated as noise and follow the
## same mapping, but they do not get to define a palette slot.
MIN_SHARE = 0.005


def luma(c) -> float:
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def palette(name: str) -> list:
    counts = collections.Counter()
    for path in glob.glob(str(CHARACTERS / name / "**" / "*.png"), recursive=True):
        image = Image.open(path).convert("RGBA")
        pixels = image.load()
        width, height = image.size
        for x in range(width):
            for y in range(height):
                r, g, b, a = pixels[x, y]
                if a > 200:
                    counts[(r, g, b)] += 1
    total = sum(counts.values())
    keep = [c for c, n in counts.items() if n / total >= MIN_SHARE]
    return sorted(keep or list(counts), key=luma)


def main() -> int:
    source_name, reference_name = sys.argv[1], sys.argv[2]
    reference = palette(reference_name)
    source = palette(source_name)
    if not reference or not source:
        print("empty palette - check the character names")
        return 1

    # Rank-match: darkest source colour to darkest reference colour, and so on, so
    # relative shading survives even when the two palettes are different sizes.
    mapping = {}
    for i, colour in enumerate(source):
        position = i / max(1, len(source) - 1)
        target = reference[round(position * (len(reference) - 1))]
        mapping[colour] = target

    def nearest(colour):
        if colour in mapping:
            return mapping[colour]
        best = min(source, key=lambda c: sum((c[i] - colour[i]) ** 2 for i in range(3)))
        return mapping[best]

    changed = 0
    for path in glob.glob(str(CHARACTERS / source_name / "**" / "*.png"), recursive=True):
        image = Image.open(path).convert("RGBA")
        pixels = image.load()
        width, height = image.size
        touched = False
        for x in range(width):
            for y in range(height):
                r, g, b, a = pixels[x, y]
                if a <= 200:
                    continue
                new = nearest((r, g, b))
                if (r, g, b) != new:
                    pixels[x, y] = (new[0], new[1], new[2], a)
                    touched = True
        if touched:
            image.save(path)
            changed += 1

    print(f"{source_name}: {len(source)} colours -> {reference_name}'s {len(reference)}, "
          f"{changed} files rewritten")
    print(f"  outline {source[0]} -> {mapping[source[0]]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
